version: '3.8'
services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: rest_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 567234
    ports:
      - "5432:5432"
  python-app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - postgres